let reStacks = ["This my excavation and to-",
    "day is Qumran",
    "Everything that happens is from now on",
    "This is pouring rain",
    "This is paralyzed",
    "I keep throwing it down, two",
    "Hundred at a time",
    "It's hard to find it when you knew it",
    "When your money's gone",
    "And you're drunk as hell",
    "On your back with your racks as he stacks your load",
    "In the back with the racks and he stacks your load",
    "In the back with the racks and you're unstacking your load",
    "I've been twisting to the sun",
    "I needed to replace",
    "And the fountain in the front yard is rusted out",
    "All my love was down",
    "In a frozen ground",
    "There's a black crow sitting across from me",
    "His wiry legs are crossed",
    "He's dangling my keys, he even fakes a toss",
    "Whatever could it be",
    "That has brought me to this loss?",
    "On your back with your racks as he stacks your load",
    "In the back with the racks and he stacks your load",
    "In the back with the racks and you're unstacking your load",
    "This is not the sound of a new man",
    "Or a crispy realization",
    "It's the sound of me unlocking and you lift away",
    "Your love will be",
    "Safe with me."];

let crEEks = [
    "Down along the creek",
    "I remember something",
    "Her, the heron hurried away",
    "When first I breached that last Sunday",
    "Low moon don the yellow road",
    "I remember something",
    "That leaving wasn't easing all that heaving in my vines",
    "And as certain it is evening 'at is now is not the time",
    "Toiling with your blood",
    "I remember something",
    "In B, un-rationed kissing on night second to last",
    "Finding both you hands as second sun came past the glass",
    "And oh, I knew it felt right",
    "I had you in my grasp",
    "Oh, then how we gonna cry?",
    "Cause it once might not mean something?",
    "Love, a second glance",
    "It is not something that we need.",
    "Honey, understand that I have been left here in the reeds",
    "And all I'm trying to do is get my feet out from the crease",
    "And I'll see you",
    "Turn around, you're my A Team",
    "Turn around now, you're my A Team",
    "Goddamn, turn around now",
    "You're my A Team."
]


let oMeOLife = [
    "Oh me! Oh life! of the questions of these recurring Of the endless trains of the faithless, of cities fill’d with the foolish",
    "Of myself forever reproaching myself, (for who more foolish than I, and who more faithless?)",
    "Of eyes that vainly crave the light, of the objects mean, of the struggle ever renew’d",
    "Of the poor results of all, of the plodding and sordid crowds I see around me",
    "Of the empty and useless years of the rest, with the rest me intertwined",
    "The question, O me! so sad, recurring—What good amid these, O me, O life?",
    "Answer.",
    "That you are here",
    "—that life exists and identity,",
    "That the powerful play goes on, and you may contribute a verse."
]

let typeWriter = new Typewriter(reStacks, document.getElementById('text'));

typeWriter.play();
